services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --port 8080 --host 0.0.0.0 --livereload
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development